version: '2'

services:

  doc:
    image: httpd:alpine
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./apispec:/usr/local/apache2/htdocs/

  api:
    image: golang:alpine
    restart: always
    ports:
      - 8080:8080
    working_dir: /go/src/github.com/isaacomy/ralali
    environment:
      DATABASE_URL: root:toor@tcp(db:3306)/ralali?charset=utf8&parseTime=True&loc=Local
    command: go run cmd/products-service-server/main.go --port=8080 --host=0.0.0.0
    volumes:
      - .:/go/src/github.com/isaacomy/ralali

  db:
    image: mariadb:10.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql