// Code generated by go-swagger; DO NOT EDIT.

package product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/isaacomy/ralali/models"
)

// DeleteProductsIDOKCode is the HTTP code returned for type DeleteProductsIDOK
const DeleteProductsIDOKCode int = 200

/*DeleteProductsIDOK Sends Product data

swagger:response deleteProductsIdOK
*/
type DeleteProductsIDOK struct {

	/*
	  In: Body
	*/
	Payload *DeleteProductsIDOKBody `json:"body,omitempty"`
}

// NewDeleteProductsIDOK creates DeleteProductsIDOK with default headers values
func NewDeleteProductsIDOK() *DeleteProductsIDOK {

	return &DeleteProductsIDOK{}
}

// WithPayload adds the payload to the delete products Id o k response
func (o *DeleteProductsIDOK) WithPayload(payload *DeleteProductsIDOKBody) *DeleteProductsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete products Id o k response
func (o *DeleteProductsIDOK) SetPayload(payload *DeleteProductsIDOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteProductsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteProductsIDBadRequestCode is the HTTP code returned for type DeleteProductsIDBadRequest
const DeleteProductsIDBadRequestCode int = 400

/*DeleteProductsIDBadRequest Bad Request / Validation exception

swagger:response deleteProductsIdBadRequest
*/
type DeleteProductsIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewDeleteProductsIDBadRequest creates DeleteProductsIDBadRequest with default headers values
func NewDeleteProductsIDBadRequest() *DeleteProductsIDBadRequest {

	return &DeleteProductsIDBadRequest{}
}

// WithPayload adds the payload to the delete products Id bad request response
func (o *DeleteProductsIDBadRequest) WithPayload(payload *models.ErrorMessage) *DeleteProductsIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete products Id bad request response
func (o *DeleteProductsIDBadRequest) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteProductsIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteProductsIDNotFoundCode is the HTTP code returned for type DeleteProductsIDNotFound
const DeleteProductsIDNotFoundCode int = 404

/*DeleteProductsIDNotFound Not found

swagger:response deleteProductsIdNotFound
*/
type DeleteProductsIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewDeleteProductsIDNotFound creates DeleteProductsIDNotFound with default headers values
func NewDeleteProductsIDNotFound() *DeleteProductsIDNotFound {

	return &DeleteProductsIDNotFound{}
}

// WithPayload adds the payload to the delete products Id not found response
func (o *DeleteProductsIDNotFound) WithPayload(payload *models.ErrorMessage) *DeleteProductsIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete products Id not found response
func (o *DeleteProductsIDNotFound) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteProductsIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteProductsIDUnprocessableEntityCode is the HTTP code returned for type DeleteProductsIDUnprocessableEntity
const DeleteProductsIDUnprocessableEntityCode int = 422

/*DeleteProductsIDUnprocessableEntity Unprocessable Entity

swagger:response deleteProductsIdUnprocessableEntity
*/
type DeleteProductsIDUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewDeleteProductsIDUnprocessableEntity creates DeleteProductsIDUnprocessableEntity with default headers values
func NewDeleteProductsIDUnprocessableEntity() *DeleteProductsIDUnprocessableEntity {

	return &DeleteProductsIDUnprocessableEntity{}
}

// WithPayload adds the payload to the delete products Id unprocessable entity response
func (o *DeleteProductsIDUnprocessableEntity) WithPayload(payload *models.ErrorMessage) *DeleteProductsIDUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete products Id unprocessable entity response
func (o *DeleteProductsIDUnprocessableEntity) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteProductsIDUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteProductsIDDefault Error

swagger:response deleteProductsIdDefault
*/
type DeleteProductsIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewDeleteProductsIDDefault creates DeleteProductsIDDefault with default headers values
func NewDeleteProductsIDDefault(code int) *DeleteProductsIDDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteProductsIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete products ID default response
func (o *DeleteProductsIDDefault) WithStatusCode(code int) *DeleteProductsIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete products ID default response
func (o *DeleteProductsIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete products ID default response
func (o *DeleteProductsIDDefault) WithPayload(payload *models.ErrorMessage) *DeleteProductsIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete products ID default response
func (o *DeleteProductsIDDefault) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteProductsIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
