// Code generated by go-swagger; DO NOT EDIT.

package product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
)

// DeleteProductsIDHandlerFunc turns a function with the right signature into a delete products ID handler
type DeleteProductsIDHandlerFunc func(DeleteProductsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteProductsIDHandlerFunc) Handle(params DeleteProductsIDParams) middleware.Responder {
	return fn(params)
}

// DeleteProductsIDHandler interface for that can handle valid delete products ID params
type DeleteProductsIDHandler interface {
	Handle(DeleteProductsIDParams) middleware.Responder
}

// NewDeleteProductsID creates a new http.Handler for the delete products ID operation
func NewDeleteProductsID(ctx *middleware.Context, handler DeleteProductsIDHandler) *DeleteProductsID {
	return &DeleteProductsID{Context: ctx, Handler: handler}
}

/*DeleteProductsID swagger:route DELETE /products/{id} product deleteProductsId

Delete Product by ID

delete Product Data by ID

*/
type DeleteProductsID struct {
	Context *middleware.Context
	Handler DeleteProductsIDHandler
}

func (o *DeleteProductsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteProductsIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DeleteProductsIDOKBody delete products ID o k body
// swagger:model DeleteProductsIDOKBody
type DeleteProductsIDOKBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this delete products ID o k body
func (o *DeleteProductsIDOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteProductsIDOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteProductsIDOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteProductsIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
