// Code generated by go-swagger; DO NOT EDIT.

package product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/isaacomy/ralali/models"
)

// GetProductsListOKCode is the HTTP code returned for type GetProductsListOK
const GetProductsListOKCode int = 200

/*GetProductsListOK get product list

swagger:response getProductsListOK
*/
type GetProductsListOK struct {

	/*
	  In: Body
	*/
	Payload *GetProductsListOKBody `json:"body,omitempty"`
}

// NewGetProductsListOK creates GetProductsListOK with default headers values
func NewGetProductsListOK() *GetProductsListOK {

	return &GetProductsListOK{}
}

// WithPayload adds the payload to the get products list o k response
func (o *GetProductsListOK) WithPayload(payload *GetProductsListOKBody) *GetProductsListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get products list o k response
func (o *GetProductsListOK) SetPayload(payload *GetProductsListOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProductsListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetProductsListBadRequestCode is the HTTP code returned for type GetProductsListBadRequest
const GetProductsListBadRequestCode int = 400

/*GetProductsListBadRequest Bad Request / Validation exception

swagger:response getProductsListBadRequest
*/
type GetProductsListBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewGetProductsListBadRequest creates GetProductsListBadRequest with default headers values
func NewGetProductsListBadRequest() *GetProductsListBadRequest {

	return &GetProductsListBadRequest{}
}

// WithPayload adds the payload to the get products list bad request response
func (o *GetProductsListBadRequest) WithPayload(payload *models.ErrorMessage) *GetProductsListBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get products list bad request response
func (o *GetProductsListBadRequest) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProductsListBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetProductsListNotFoundCode is the HTTP code returned for type GetProductsListNotFound
const GetProductsListNotFoundCode int = 404

/*GetProductsListNotFound Not found

swagger:response getProductsListNotFound
*/
type GetProductsListNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewGetProductsListNotFound creates GetProductsListNotFound with default headers values
func NewGetProductsListNotFound() *GetProductsListNotFound {

	return &GetProductsListNotFound{}
}

// WithPayload adds the payload to the get products list not found response
func (o *GetProductsListNotFound) WithPayload(payload *models.ErrorMessage) *GetProductsListNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get products list not found response
func (o *GetProductsListNotFound) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProductsListNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetProductsListDefault Error

swagger:response getProductsListDefault
*/
type GetProductsListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewGetProductsListDefault creates GetProductsListDefault with default headers values
func NewGetProductsListDefault(code int) *GetProductsListDefault {
	if code <= 0 {
		code = 500
	}

	return &GetProductsListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get products list default response
func (o *GetProductsListDefault) WithStatusCode(code int) *GetProductsListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get products list default response
func (o *GetProductsListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get products list default response
func (o *GetProductsListDefault) WithPayload(payload *models.ErrorMessage) *GetProductsListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get products list default response
func (o *GetProductsListDefault) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProductsListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
