// Code generated by go-swagger; DO NOT EDIT.

package product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"

	"github.com/isaacomy/ralali/models"
)

// GetProductsCompareHandlerFunc turns a function with the right signature into a get products compare handler
type GetProductsCompareHandlerFunc func(GetProductsCompareParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetProductsCompareHandlerFunc) Handle(params GetProductsCompareParams) middleware.Responder {
	return fn(params)
}

// GetProductsCompareHandler interface for that can handle valid get products compare params
type GetProductsCompareHandler interface {
	Handle(GetProductsCompareParams) middleware.Responder
}

// NewGetProductsCompare creates a new http.Handler for the get products compare operation
func NewGetProductsCompare(ctx *middleware.Context, handler GetProductsCompareHandler) *GetProductsCompare {
	return &GetProductsCompare{Context: ctx, Handler: handler}
}

/*GetProductsCompare swagger:route GET /products/compare product getProductsCompare

Get Compare Product List

Get Compare Product List

*/
type GetProductsCompare struct {
	Context *middleware.Context
	Handler GetProductsCompareHandler
}

func (o *GetProductsCompare) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetProductsCompareParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetProductsCompareBody get products compare body
// swagger:model GetProductsCompareBody
type GetProductsCompareBody struct {

	// products id
	ProductsID []int64 `json:"products_id"`
}

// Validate validates this get products compare body
func (o *GetProductsCompareBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetProductsCompareBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetProductsCompareBody) UnmarshalBinary(b []byte) error {
	var res GetProductsCompareBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// GetProductsCompareOKBody get products compare o k body
// swagger:model GetProductsCompareOKBody
type GetProductsCompareOKBody struct {

	// items
	Items []*models.Product `json:"items"`

	// total items
	TotalItems float64 `json:"total_items,omitempty"`
}

// Validate validates this get products compare o k body
func (o *GetProductsCompareOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateItems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetProductsCompareOKBody) validateItems(formats strfmt.Registry) error {

	if swag.IsZero(o.Items) { // not required
		return nil
	}

	for i := 0; i < len(o.Items); i++ {
		if swag.IsZero(o.Items[i]) { // not required
			continue
		}

		if o.Items[i] != nil {
			if err := o.Items[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getProductsCompareOK" + "." + "items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetProductsCompareOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetProductsCompareOKBody) UnmarshalBinary(b []byte) error {
	var res GetProductsCompareOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
