// Code generated by go-swagger; DO NOT EDIT.

package product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"

	"github.com/isaacomy/ralali/models"
)

// PostProductsCompareHandlerFunc turns a function with the right signature into a post products compare handler
type PostProductsCompareHandlerFunc func(PostProductsCompareParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostProductsCompareHandlerFunc) Handle(params PostProductsCompareParams) middleware.Responder {
	return fn(params)
}

// PostProductsCompareHandler interface for that can handle valid post products compare params
type PostProductsCompareHandler interface {
	Handle(PostProductsCompareParams) middleware.Responder
}

// NewPostProductsCompare creates a new http.Handler for the post products compare operation
func NewPostProductsCompare(ctx *middleware.Context, handler PostProductsCompareHandler) *PostProductsCompare {
	return &PostProductsCompare{Context: ctx, Handler: handler}
}

/*PostProductsCompare swagger:route POST /products/compare product postProductsCompare

Get Compare Product List

Get Compare Product List

*/
type PostProductsCompare struct {
	Context *middleware.Context
	Handler PostProductsCompareHandler
}

func (o *PostProductsCompare) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostProductsCompareParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostProductsCompareBody post products compare body
// swagger:model PostProductsCompareBody
type PostProductsCompareBody struct {

	// products id
	ProductsID []int64 `json:"products_id"`
}

// Validate validates this post products compare body
func (o *PostProductsCompareBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostProductsCompareBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostProductsCompareBody) UnmarshalBinary(b []byte) error {
	var res PostProductsCompareBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// PostProductsCompareOKBody post products compare o k body
// swagger:model PostProductsCompareOKBody
type PostProductsCompareOKBody struct {

	// items
	Items []*models.Product `json:"items"`

	// total items
	TotalItems int64 `json:"total_items,omitempty"`
}

// Validate validates this post products compare o k body
func (o *PostProductsCompareOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateItems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostProductsCompareOKBody) validateItems(formats strfmt.Registry) error {

	if swag.IsZero(o.Items) { // not required
		return nil
	}

	for i := 0; i < len(o.Items); i++ {
		if swag.IsZero(o.Items[i]) { // not required
			continue
		}

		if o.Items[i] != nil {
			if err := o.Items[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("postProductsCompareOK" + "." + "items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostProductsCompareOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostProductsCompareOKBody) UnmarshalBinary(b []byte) error {
	var res PostProductsCompareOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
