// Code generated by go-swagger; DO NOT EDIT.

package product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/isaacomy/ralali/models"
)

// PostProductsOKCode is the HTTP code returned for type PostProductsOK
const PostProductsOKCode int = 200

/*PostProductsOK Insert New Product

swagger:response postProductsOK
*/
type PostProductsOK struct {

	/*
	  In: Body
	*/
	Payload *PostProductsOKBody `json:"body,omitempty"`
}

// NewPostProductsOK creates PostProductsOK with default headers values
func NewPostProductsOK() *PostProductsOK {

	return &PostProductsOK{}
}

// WithPayload adds the payload to the post products o k response
func (o *PostProductsOK) WithPayload(payload *PostProductsOKBody) *PostProductsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post products o k response
func (o *PostProductsOK) SetPayload(payload *PostProductsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostProductsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostProductsBadRequestCode is the HTTP code returned for type PostProductsBadRequest
const PostProductsBadRequestCode int = 400

/*PostProductsBadRequest Bad Request / Validation exception

swagger:response postProductsBadRequest
*/
type PostProductsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewPostProductsBadRequest creates PostProductsBadRequest with default headers values
func NewPostProductsBadRequest() *PostProductsBadRequest {

	return &PostProductsBadRequest{}
}

// WithPayload adds the payload to the post products bad request response
func (o *PostProductsBadRequest) WithPayload(payload *models.ErrorMessage) *PostProductsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post products bad request response
func (o *PostProductsBadRequest) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostProductsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostProductsDefault Error

swagger:response postProductsDefault
*/
type PostProductsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewPostProductsDefault creates PostProductsDefault with default headers values
func NewPostProductsDefault(code int) *PostProductsDefault {
	if code <= 0 {
		code = 500
	}

	return &PostProductsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post products default response
func (o *PostProductsDefault) WithStatusCode(code int) *PostProductsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post products default response
func (o *PostProductsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post products default response
func (o *PostProductsDefault) WithPayload(payload *models.ErrorMessage) *PostProductsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post products default response
func (o *PostProductsDefault) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostProductsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
