// Code generated by go-swagger; DO NOT EDIT.

package product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
)

// PutProductsIDHandlerFunc turns a function with the right signature into a put products ID handler
type PutProductsIDHandlerFunc func(PutProductsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutProductsIDHandlerFunc) Handle(params PutProductsIDParams) middleware.Responder {
	return fn(params)
}

// PutProductsIDHandler interface for that can handle valid put products ID params
type PutProductsIDHandler interface {
	Handle(PutProductsIDParams) middleware.Responder
}

// NewPutProductsID creates a new http.Handler for the put products ID operation
func NewPutProductsID(ctx *middleware.Context, handler PutProductsIDHandler) *PutProductsID {
	return &PutProductsID{Context: ctx, Handler: handler}
}

/*PutProductsID swagger:route PUT /products/{id} product putProductsId

Update Product by ID

Update Product by ID

*/
type PutProductsID struct {
	Context *middleware.Context
	Handler PutProductsIDHandler
}

func (o *PutProductsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutProductsIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PutProductsIDBody put products ID body
// swagger:model PutProductsIDBody
type PutProductsIDBody struct {

	// categories id
	Catogories []int64 `json:"catogories"`

	// name
	Name string `json:"name,omitempty"`

	// series
	Series string `json:"series,omitempty"`
}

// Validate validates this put products ID body
func (o *PutProductsIDBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PutProductsIDBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutProductsIDBody) UnmarshalBinary(b []byte) error {
	var res PutProductsIDBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
