// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
)

// DeleteCategoryIDHandlerFunc turns a function with the right signature into a delete category ID handler
type DeleteCategoryIDHandlerFunc func(DeleteCategoryIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteCategoryIDHandlerFunc) Handle(params DeleteCategoryIDParams) middleware.Responder {
	return fn(params)
}

// DeleteCategoryIDHandler interface for that can handle valid delete category ID params
type DeleteCategoryIDHandler interface {
	Handle(DeleteCategoryIDParams) middleware.Responder
}

// NewDeleteCategoryID creates a new http.Handler for the delete category ID operation
func NewDeleteCategoryID(ctx *middleware.Context, handler DeleteCategoryIDHandler) *DeleteCategoryID {
	return &DeleteCategoryID{Context: ctx, Handler: handler}
}

/*DeleteCategoryID swagger:route DELETE /category/{id} category deleteCategoryId

Delete Category by ID

delete Category Data by ID

*/
type DeleteCategoryID struct {
	Context *middleware.Context
	Handler DeleteCategoryIDHandler
}

func (o *DeleteCategoryID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteCategoryIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DeleteCategoryIDOKBody delete category ID o k body
// swagger:model DeleteCategoryIDOKBody
type DeleteCategoryIDOKBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this delete category ID o k body
func (o *DeleteCategoryIDOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteCategoryIDOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteCategoryIDOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteCategoryIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
