// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/isaacomy/ralali/models"
)

// GetCategoryListOKCode is the HTTP code returned for type GetCategoryListOK
const GetCategoryListOKCode int = 200

/*GetCategoryListOK get category list

swagger:response getCategoryListOK
*/
type GetCategoryListOK struct {

	/*
	  In: Body
	*/
	Payload *GetCategoryListOKBody `json:"body,omitempty"`
}

// NewGetCategoryListOK creates GetCategoryListOK with default headers values
func NewGetCategoryListOK() *GetCategoryListOK {

	return &GetCategoryListOK{}
}

// WithPayload adds the payload to the get category list o k response
func (o *GetCategoryListOK) WithPayload(payload *GetCategoryListOKBody) *GetCategoryListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get category list o k response
func (o *GetCategoryListOK) SetPayload(payload *GetCategoryListOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCategoryListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCategoryListBadRequestCode is the HTTP code returned for type GetCategoryListBadRequest
const GetCategoryListBadRequestCode int = 400

/*GetCategoryListBadRequest Bad Request / Validation exception

swagger:response getCategoryListBadRequest
*/
type GetCategoryListBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewGetCategoryListBadRequest creates GetCategoryListBadRequest with default headers values
func NewGetCategoryListBadRequest() *GetCategoryListBadRequest {

	return &GetCategoryListBadRequest{}
}

// WithPayload adds the payload to the get category list bad request response
func (o *GetCategoryListBadRequest) WithPayload(payload *models.ErrorMessage) *GetCategoryListBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get category list bad request response
func (o *GetCategoryListBadRequest) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCategoryListBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCategoryListNotFoundCode is the HTTP code returned for type GetCategoryListNotFound
const GetCategoryListNotFoundCode int = 404

/*GetCategoryListNotFound Not found

swagger:response getCategoryListNotFound
*/
type GetCategoryListNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewGetCategoryListNotFound creates GetCategoryListNotFound with default headers values
func NewGetCategoryListNotFound() *GetCategoryListNotFound {

	return &GetCategoryListNotFound{}
}

// WithPayload adds the payload to the get category list not found response
func (o *GetCategoryListNotFound) WithPayload(payload *models.ErrorMessage) *GetCategoryListNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get category list not found response
func (o *GetCategoryListNotFound) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCategoryListNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetCategoryListDefault Error

swagger:response getCategoryListDefault
*/
type GetCategoryListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewGetCategoryListDefault creates GetCategoryListDefault with default headers values
func NewGetCategoryListDefault(code int) *GetCategoryListDefault {
	if code <= 0 {
		code = 500
	}

	return &GetCategoryListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get category list default response
func (o *GetCategoryListDefault) WithStatusCode(code int) *GetCategoryListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get category list default response
func (o *GetCategoryListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get category list default response
func (o *GetCategoryListDefault) WithPayload(payload *models.ErrorMessage) *GetCategoryListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get category list default response
func (o *GetCategoryListDefault) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCategoryListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
