// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Price price
// swagger:model Price
type Price struct {

	// id
	ID int64 `json:"id,omitempty" gorm:"primary_key"`

	// min quantity
	MinQuantity int64 `json:"min_quantity,omitempty"`

	// price
	Price float64 `json:"price,omitempty"`

	// product id
	ProductID int64 `json:"product_id,omitempty"`

	// status
	Status int64 `json:"status,omitempty"`
}

// Validate validates this price
func (m *Price) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Price) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Price) UnmarshalBinary(b []byte) error {
	var res Price
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
