// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProductHasCategory product has category
// swagger:model ProductHasCategory
type ProductHasCategory struct {

	// category id
	CategoryID int64 `json:"category_id,omitempty"`

	// product id
	ProductID int64 `json:"product_id,omitempty"`
}

// Validate validates this product has category
func (m *ProductHasCategory) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProductHasCategory) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProductHasCategory) UnmarshalBinary(b []byte) error {
	var res ProductHasCategory
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
